### ISSUE TITLE
PheonixTool expand broke

### ISSUE THREAD

**Issue by sugoidogo** [HaloMods/HaloWarsDocs#4]
```
phxtool.exe --env=phx --tool=era --mode=expand --path="C:\Users\Josef\Documents\Halo Wars Mods\vanilla\root" --out="C:\Users\Josef\Documents\Halo Wars Mods\vanilla" --name=root
Era:Expander: Treating ERA as 64-bit (Definitive Edition)
	Removing XMB file #1652 'art\effects\shield_dome\shield_fade_fast_01.xml.xmb' from listing since its XML already exists art\effects\shield_dome\shield_fade_fast_01.xml
	Removing XMB file #1653 'art\effects\shield_dome\shield_flicker_animation_01.xml.xmb' from listing since its XML already exists art\effects\shield_dome\shield_flicker_animation_01.xml
	Encountered an error while expanding archive: System.ArgumentNullException: Buffer cannot be null.
Parameter name: buffer
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at KSoft.Phoenix.Resource.EraFile.TransformXmbToXml(Byte[] eraFileEntryBuffer, String fullPath, EndianFormat byteOrder, ProcessorSize vaSize)
   at KSoft.Phoenix.Resource.EraFile.UnpackToDisk(EndianStream blockStream, String fullPath, EraFileExpander expander, EraFileEntryChunk file)
   at KSoft.Phoenix.Resource.EraFile.TryUnpack(EndianStream blockStream, String workPath, EraFileExpander expander, EraFileEntryChunk file)
   at KSoft.Phoenix.Resource.EraFile.ExpandTo(EndianStream blockStream, String workPath)
   at KSoft.Phoenix.Resource.EraFileExpander.ExpandTo(String workPath, String listingName)
```

**Comment by kornman00** [comment]
Do you still have issues with 1.0.8's binaries?

**Comment by sugoidogo** [comment]
I never actually got around to testing your new binaries. I'll have to re-install HWDE and get my dev env set up again (I had to wipe my pc recently)

**Comment by sugoidogo** [comment]
Looks like same error in phxtool.exe

```
Input:  C:\Program Files (x86)\Steam\steamapps\common\HaloWarsDE\root.era
Output: C:\Users\Josef\Documents\Halo Wars Mods\vanilla\root.era.bin
phxtool.exe --env=phx --tool=era --mode=expand --path="C:\Users\Josef\Documents\Halo Wars Mods\vanilla\root" --out="C:\Users\Josef\Documents\Halo Wars Mods\vanilla" --name=root
Era:Expander: Treating ERA as 64-bit (Definitive Edition)
	Removing XMB file #1652 'art\effects\shield_dome\shield_fade_fast_01.xml.xmb' from listing since its XML already exists art\effects\shield_dome\shield_fade_fast_01.xml
	Removing XMB file #1653 'art\effects\shield_dome\shield_flicker_animation_01.xml.xmb' from listing since its XML already exists art\effects\shield_dome\shield_flicker_animation_01.xml
	Encountered an error while expanding archive: System.ArgumentNullException: Buffer cannot be null.
Parameter name: buffer
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at KSoft.Phoenix.Resource.EraFile.TransformXmbToXml(Byte[] eraFileEntryBuffer, String fullPath, EndianFormat byteOrder, ProcessorSize vaSize)
   at KSoft.Phoenix.Resource.EraFile.UnpackToDisk(EndianStream blockStream, String fullPath, EraFileExpander expander, EraFileEntryChunk file)
   at KSoft.Phoenix.Resource.EraFile.TryUnpack(EndianStream blockStream, String workPath, EraFileExpander expander, EraFileEntryChunk file)
   at KSoft.Phoenix.Resource.EraFile.ExpandTo(EndianStream blockStream, String workPath)
   at KSoft.Phoenix.Resource.EraFileExpander.ExpandTo(String workPath, String listingName)
```

**Comment by kornman00** [comment]
Sorry :(, I'll looking fixing it later this week (hopefully!)

**Comment by kornman00** [comment]
Granted, I haven't tried debugging the 2018 binaries that are currently up, but running the following command with the 8th switch set to true (to decrypt the era in-place) with the latest code works:
`--env=phx --tool=era --mode=expand --path="D:\SteamLibrary\steamapps\common\HaloWarsDE\root" --out="D:\HW\HWDE\Test" --name=root --switches=00000001`

```
Era:Expander: Switch enabled - ERA will be loaded into memory and decrypted in place
Era:Expander: Treating ERA as 64-bit (Definitive Edition)
Opening and reading ERA file D:\SteamLibrary\steamapps\common\HaloWarsDE\root.era...
Decrypting...
        Verifying file hashes...
                Done
Removing any XMB files if their XML counterpart exists...
        Removing XMB file #1652 'art\effects\shield_dome\shield_fade_fast_01.xml.xmb' from listing since its XML already exists art\effects\shield_dome\shield_fade_fast_01.xml
        Removing XMB file #1653 'art\effects\shield_dome\shield_flicker_animation_01.xml.xmb' from listing since its XML already exists art\effects\shield_dome\shield_flicker_animation_01.xml
Outputting listing...
Expanding archive to D:\HW\HWDE\Test...
        Unpacking files...
                Done
Done
Done
```

**Comment by kornman00** [comment]
The exception looks very similar to the one reported via PhxGui in #5 , which I am not able to repro on latest code either.
