### ISSUE TITLE
xmb-xml issue 

### ISSUE THREAD

**Issue by JAIxSPARTANx006** [HaloMods/HaloWarsDocs#5]
EXCEPTION C:\Users\JAI's gaming beast\AppData\Local\Packages\Microsoft.BulldogThreshold_8wekyb3d8bbwe\LocalState\backups\data\powers\unscunitcarpetbomb.power.xmb
System.ArgumentNullException: Buffer cannot be null.
Parameter name: buffer
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at KSoft.Phoenix.Resource.ECF.EcfFileXmb.XmbToXml(EndianStream xmbStream, Stream outputStream, ProcessorSize vaSize)
   at KSoft.Phoenix.Resource.ResourceUtils.XmbToXml(EndianStream xmbStream, Stream outputStream, ProcessorSize vaSize)
   at PhxGui.MainWindowViewModel.XmlConverter.ConvertXmbToXml(String xmlFile, String xmbFile)
   at PhxGui.MainWindowViewModel.XmlConverter.<Convert>b__15_0(String f)

I try to  drag and drop .xmb file into the phxgui tool and the message above happens 

I am hoping you can help thx
![capture1](https://user-images.githubusercontent.com/46058797/51277923-e552c200-198d-11e9-8192-25ae56345fcb.PNG)

**Comment by ACarey1836** [comment]
I'm having the same problem. I can't seem to figure it out.

**Comment by kornman00** [comment]
Testing with the latest code, I'm not hitting this issue. Not sure when I'll upload new binaries next though.

**Comment by kornman00** [comment]
I tried reproing this more closely (again, on some latest code), where I installed the WinStore version of the game, ran it, then expanded my Steam copy's root.era to my `AppData\Local\Packages\Microsoft.BulldogThreshold_8wekyb3d8bbwe\LocalState\backups\data`. I then drag and dropped the fresh skulls.xml.xmb and it successfully created skulls.xml.

Either this was an issue specific to a previous release, or there's something else that causes this problem to trigger.
